export const SET_MOBILE_MEGA_MENU = "SET_MOBILE_MEGA_MENU";
export const SET_MOBILE_MEGA_MENU_LOADING = "SET_MOBILE_MEGA_MENU_LOADING";
export const SET_MOBILE_MEGA_MENU_ERROR = "SET_MOBILE_MEGA_MENU_ERROR";