export const SET_AMAZING_CRUD = "SET_AMAZING_CRUD";
export const SET_AMAZING_CRUD_LOADING = "SET_AMAZING_CRUD_LOADING";
export const SET_AMAZING_CRUD_ERROR = "SET_AMAZING_CRUD_ERROR";

export const ADD_AMAZING_CRUD_SLIDE = "ADD_AMAZING_CRUD_SLIDE";
export const UPDATE_AMAZING_CRUD_SLIDE = "UPDATE_AMAZING_CRUD_SLIDE";
export const DELETE_AMAZING_CRUD_SLIDE = "DELETE_AMAZING_CRUD_SLIDE";